[auth]
allowed_redirect_urls = [
  "http://localhost:3010/admin/careers/login",
  "http://localhost:3010/admin/careers/new-password",
  "http://localhost:3010/admin/careers/verify-code",
  "https://radassistpro.com/admin/careers/login",
  "https://radassistpro.com/admin/careers/new-password",
  "https://radassistpro.com/admin/careers/verify-code",
  "https://www.radassistpro.com/admin/careers/login",
  "https://www.radassistpro.com/admin/careers/new-password",
  "https://www.radassistpro.com/admin/careers/verify-code",
]
require_email_verification = false
verify_email_method = "code"
reset_password_method = "code"
disable_signup = false

[auth.password]
min_length = 12
require_number = true
require_lowercase = true
require_uppercase = true
require_special_char = true

[auth.smtp]
enabled = false
host = ""
port = 465
username = ""
sender_email = ""
sender_name = ""
min_interval_seconds = 60

[storage]
max_file_size_mb = 50

[realtime]
retention_days = 0

[schedules]
retention_days = 7
